### ISSUE TITLE
안녕하십니까~!

### ISSUE THREAD

**Issue by imdaeseok** [TheKoguryo/TheKoguryo.github.io#1]
안녕하세요~! 고구료님~! 
OCI에 인스턴스에 APP을 올린후 계정 A,B가 API를 통해서 접근할때 서로 다른 계정이므로 서로 다른 ocid로 인해 타 인스턴스에 대한 정보는 볼 수 없음을 증명하려고 하는데요~! 
고구료님 블로그의 어떤 부분을 참고하면 좋을까요 ? 
제가 찾아본 바로는 14.3의 REST API 가 유력하다고 생각되는데 
관련 레퍼런스 추천해주시면 감사하겠습니다.

**Comment by TheKoguryo** [comment]
안녕하세요, 이제 봤습니다. 많이 늦었네요.

해결 하신 건가요?

사용자 계정 A,B를 사용하여 OCI REST API(또는 OCI CLI)로 조회할 때, 다른 유저가 만든 Compute Instance 는  조회가 되지 않는 다는 걸 확인하고 싶다는 질문이신가요?

질문이 맞다면, 계정 A,B의 권한에 따라 결과가 달라질것 같습니다. A는 CompartmentA에 Compute Instance #1를 만들고, B는 CompartmentB에 Compute Instance #2를 만든경우, 사용자 A가 CompartmentA에 있는 Compute 자원에 대한 조회권한만 있으면, Compute Instance #1만 보일 것이고, CompartmentB에 대한 조회권한도 있다고 하면,  Compute Instance #1, #2 모두 보이게 됩니다.

감사합니다.
