### ISSUE TITLE
"4.1 Reserved Public IP 만들기"의 오류

### ISSUE THREAD

**Issue by odinox-naver-com** [TheKoguryo/TheKoguryo.github.io#2]
안녕하세요
정리가 너무 깔끔해서 하나하나 따라가면 해 보고 있습니다.
다만,
4.1 Reserved Public IP 만들기
에서 OCI 에서 잡아둔 IP 가 모두 소진되었는지.
"The following service limits were exceeded: reserved-public-ip-count. Request a service limit increase from the service limits page in the console."
이런 에러가 나고 있습니다.

Service Limits 페이지에 가보면..
Free-tier 라서 요청할 수 없다는 말이 나오고요;;

앞 장에서
"Ephemeral Public IP : 일시적인 공인 IP로 일반적으로 Instance의 시작할 때 부여되며, 종료될 때까지 변경되지 않습니다."

이렇게 설명을 해 주셔서..
그렇다면 그냥 Ephemeral Public IP 를 써도 되는 건가 하는 생각이 드는데요..
종료를 안 시키면 되니깐...

어떤가요? 아니면 다른 해결 방안이 있을까요?

**Comment by TheKoguryo** [comment]
@odinox-naver-com

안녕하세요, 이제 봤습니다.

Governance & Administration >> Limits, Quotas and Usage >> Service: Virtual Cloud Network 선택 >> Scope: Region 선택하면,
Reserved Public IP Count의 현재 Limit을 볼 수 있습니다.
Always Free에서는 Limit를 늘릴수 없습니다. 늘릴려면 Paid로 전환해야 합니다. 아마 1개는 제공할텐데요...

https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/managingpublicIPs.htm
You can unassign it at any time, which deletes it. You might do this if whoever launched the instance included a public IP, but you don't want the instance to have one.
When you stop an instance, its ephemeral public IPs remain assigned to the instance.

위 문서의 "Types of Public IPs"의 설명 부분 표에서 보면 Unassignment 항목에서 설명하고 있는 내용을 보면,
unassign하면 "Ephemeral Public IP"은 더 이상 소유할 수 없다.
Compute 인스턴스에 assign된 상태에서는 stop을 해도 인스턴스에 할당된 상태로 있게된다.
종료(Terminate) 시키지 않고, 중지, 재시작 하면 그대로 사용할 수 있습니다.

아니면, 외부에 가지고 계신 DNS가 있으면, 그쪽에 등록해서 DNS Name으로 사용하셔도 됩니다.

감사합니다,
